// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8dFkCC9ReMlLxb8IYMYO7uKGg0EZT730',
    appId: '1:312223417322:web:dd7a56efa57f8bab9d2893',
    messagingSenderId: '312223417322',
    projectId: 'nhom11-d382b',
    authDomain: 'nhom11-d382b.firebaseapp.com',
    databaseURL: 'https://nhom11-d382b-default-rtdb.firebaseio.com',
    storageBucket: 'nhom11-d382b.firebasestorage.app',
    measurementId: 'G-Q6GGN9F8VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwDHBI79-oj64x6DjCQ5XiZqcyFhIg6nw',
    appId: '1:312223417322:android:bc1f32f29cee323d9d2893',
    messagingSenderId: '312223417322',
    projectId: 'nhom11-d382b',
    databaseURL: 'https://nhom11-d382b-default-rtdb.firebaseio.com',
    storageBucket: 'nhom11-d382b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsVwniEFFum2xK3mV8E3JGdGzJ1Cp6gGI',
    appId: '1:312223417322:ios:a9d365549809f5be9d2893',
    messagingSenderId: '312223417322',
    projectId: 'nhom11-d382b',
    databaseURL: 'https://nhom11-d382b-default-rtdb.firebaseio.com',
    storageBucket: 'nhom11-d382b.firebasestorage.app',
    iosBundleId: 'com.example.nhom11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsVwniEFFum2xK3mV8E3JGdGzJ1Cp6gGI',
    appId: '1:312223417322:ios:a9d365549809f5be9d2893',
    messagingSenderId: '312223417322',
    projectId: 'nhom11-d382b',
    databaseURL: 'https://nhom11-d382b-default-rtdb.firebaseio.com',
    storageBucket: 'nhom11-d382b.firebasestorage.app',
    iosBundleId: 'com.example.nhom11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8dFkCC9ReMlLxb8IYMYO7uKGg0EZT730',
    appId: '1:312223417322:web:1a606a616455830e9d2893',
    messagingSenderId: '312223417322',
    projectId: 'nhom11-d382b',
    authDomain: 'nhom11-d382b.firebaseapp.com',
    databaseURL: 'https://nhom11-d382b-default-rtdb.firebaseio.com',
    storageBucket: 'nhom11-d382b.firebasestorage.app',
    measurementId: 'G-NJ290G8J8H',
  );
}
